# generated by zon2nix (https://github.com/nix-community/zon2nix)
# NOTE: chameleon is vendored at vendor/chameleon (path dependency),
# so it does not need a fetch entry here.

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "toml-0.3.0-bV14BRmKAQAWR0FT0KUKFwVJTImaFhWjSe6HfSMtNZOH";
    path = fetchgit {
      url = "https://github.com/sam701/zig-toml";
      rev = "8685923e32e8b8a795eb2715684236975a70faed";
      hash = "sha256-MU+zI9Utu7VaLy9hmyhRZXstfAPUjMSblE8SWLmrK6o=";
    };
  }
  {
    name = "yazap-0.7.0-Z1t-EiT6AQDpbgaDQ1i_oBfnvmeH4AUM3WmiuTuXuQMN";
    path = fetchgit {
      url = "https://github.com/prajwalch/yazap";
      rev = "82edda4aa180cc3aebf00b2c39a37975969eba0a";
      hash = "sha256-5cqzpwcU7gRM+eH9EJMmCxL5XjmahtNVZ8jO1mvXdHE=";
    };
  }
]
