# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "chameleon-2.0.1-ZOxajZ17AADmYCpHFqqoGfaXQiRkXM8B5lYJfir9tqsz";
    path = fetchgit {
      url = "https://github.com/tr1ckydev/chameleon";
      rev = "414169dede742d9ac8261d31b9fca6e31a1d7246";
      hash = "sha256-/TGzbVh+Z6dPEKtW0M0Tv1vXvc6jmb+kHf6Q0rHmEPE=";
    };
  }
  {
    name = "toml-0.3.0-bV14BeiEAQBmkb-ywYhHxpBdt52ztkRmf-EVyEFbrTxt";
    path = fetchgit {
      url = "https://github.com/sam701/zig-toml";
      rev = "44318b82b961cb3c09a23924c2de80b9192213bd";
      hash = "sha256-VebYCCbwdaiwa2l276eAO3UysL2/5kisptiq4ZkBxAI=";
    };
  }
  {
    name = "yazap-0.6.3-Z1t-Emb0AQD_SkYf4dz_nEmAh9oRKiu6nexSJMGK3wcf";
    path = fetchgit {
      url = "https://github.com/prajwalch/yazap";
      rev = "a920616e3a6676362735a2f5ae195ec320f058fb";
      hash = "sha256-THVkDGnFjgLfHeZ6FpR6LIEiQ0gIgIQYK33oBq6xIgo=";
    };
  }
]
